version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: examplepassword
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - redis
      - db
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      REDIS_URL: redis://redis
      PGUSER: postgres
      PGHOST: db
      PGDATABASE: postgres
      PGPASSWORD: examplepassword
      PGPORT: "5432"
